/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp } from 'firebase/app';
import { getAuth, setPersistence, browserLocalPersistence } from 'firebase/auth';

// Safely import the Firebase config generated by the setup tool
import firebaseConfig from '../../firebase-applet-config.json';

// Initialize Client-Side Firebase App
const app = initializeApp(firebaseConfig);

// Initialize Client-Side Firebase Auth with Local Persistence
export const auth = getAuth(app);
setPersistence(auth, browserLocalPersistence).catch((err) => {
  console.error("Failed to establish auth persistence:", err);
});
